zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    file-service:
        path: /files/**
        url: http://localhost:6000
        serviceId: file-service
        stripPrefix: false
        sensitiveHeaders:

    file-list-service:
        path: /file-list/**
        url: http://localhost:9000
        serviceId: file-list-service
        stripPrefix: false
        sensitiveHeaders:

    type-size-info-service:
        path: /type-size-info/**
        url: http://localhost:8000
        serviceId: type-size-info-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000
  tomcat:
      basedir: ${user.home}/tmp/tomcat

spring:
  servlet:
    multipart:
      location: /src/temp
      max-file-size: -1
      maxr-equest-size: -1